spring:
  application:
    name: micro_market

  datasource:
    url: jdbc:mysql://localhost:3306/micro_market
    username: root
    password: Di1004960034.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format-sql: true

server:
  port: 8484
  servlet:
    context-path: /api/v1/micro_market  