spring:
  application:
    name: mini-market

  
  # conexion a la base de datos
  datasource:
    url: jdbc:mysql://localhost:3306/micro_market
    username: root
    password: 1005367136md
    driver-class-name: com.mysql.cj.jdbc.Driver


  #configuracion del puerto
server:
    port: 9090
    servlet:
      context-path: /api/v1/micro_market


loggin: # sección de logs
  level: # niveles de logs
    org.springframework.web: DEBUG # Logs detallados para web
    org.springframework.jdbc.core.JdbcTemplate: DEBUG # Muestra queries SQL
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE