spring:
  application:
    name: mini-market

  
  # conexion a la base de datos
  datasource:
    url: jdbc:mysql://localhost:3306/micro_market
    username: root
    password: 1005367136md
    driver-class-name: com.mysql.cj.jdbc.Driver


  #configuracion del puerto
server:
    port: 9090
    servlet:
      context-path: /api/v1/micro_market